### ISSUE TITLE
roc: byKindAndId

### ISSUE THREAD

**Issue by maasencioh** [cheminfo-js/visualizer-helper#16]
currently is not added the option to use the `byKindAndId` mentioned in [the API](https://github.com/cheminfo/rest-on-couch/blob/master/API.md#queries)

**Comment by stropitek** [comment]
I don't remember why this route exists but you can achieve the same result using `roc.view`:
```js
roc.view('entryByKindAndId', {key: ['mykind', 'myid']})
```

**Comment by maasencioh** [comment]
cool, thanks

Ps: maybe you may like to use [RAML](https://raml.org/) to document the API, it's easier to mantain and to specify the parameters as well :wink:
