### ISSUE TITLE
Strange order of calls ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/visualizer-helper#4]
I cleaned up a little bit the library but seems to me something is not normal

In line

https://github.com/cheminfo-js/visualizer-helper/blob/c5b37afbaa52911e4cdfe8d4670d62f3afa88aa4/eln/MF.js#L37

We should set the molfile but following code is executed after and seems still to have the previous value.

https://github.com/cheminfo-js/visualizer-helper/blob/c5b37afbaa52911e4cdfe8d4670d62f3afa88aa4/eln/MF.js#L37

**Comment by stropitek** [comment]
Fixed
